### ISSUE TITLE
404 (not found)

### ISSUE THREAD

**Issue by tri003** [mu-semtech/ember-paper-data-table#1]
I tried to copy the demo files and this error show when i test it.
What when wrong?

http://localhost:4200/books?page%5Bnumber%5D=0&page%5Bsize%5D=5 404 (Not Found)

Error while processing route: books Ember Data Request GET /books returned a 404
Payload (Empty Content-Type)
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Cannot GET /books</pre>
</body>
</html>
 Error: Ember Data Request GET /books returned a 404
Payload (Empty Content-Type)
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Cannot GET /books</pre>
</body>
</html>

    at ErrorClass.EmberError (http://localhost:4200/assets/vendor.js:29469:25)
    at ErrorClass.AdapterError (http://localhost:4200/assets/vendor.js:102032:15)
    at new ErrorClass (http://localhost:4200/assets/vendor.js:102053:22)
    at Class.handleResponse (http://localhost:4200/assets/vendor.js:114300:18)
    at ajaxError (http://localhost:4200/assets/vendor.js:114671:25)
    at Class.hash.error (http://localhost:4200/assets/vendor.js:114338:23)
    at fire (http://localhost:4200/assets/vendor.js:8786:31)
    at Object.fireWith [as rejectWith] (http://localhost:4200/assets/vendor.js:8916:7)
    at done (http://localhost:4200/assets/vendor.js:14825:14)
    at XMLHttpRequest.<anonymous> (http://localhost:4200/assets/vendor.js:15066:9)

**Comment by madnificent** [comment]
This was supposedly due to the backend not existing or not having been configured in the app.  Seems fair to close this issue given the time that went over it.  Do reopen or create a new one if this problem still persists.
